root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o tmp/main ./cmd/main.go"
  bin = "tmp/main"
  full_bin = "APP_ENV=dev tmp/main"
  include_ext = ["go", "tmpl", "html"]
  exclude_dir = ["script", "tmp", "docker"]

[log]
  time = true
